/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '10/7/23, 5:04 PM' 
 * Generated by 'chand' 
 * Generated on server 'CHANDU.HSD1.CT.COMCAST.NET' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:62843/main?locale=en_US&zone=GMT-04%253A00&sutoken=%257BE373F804-EBF4-4B16-BE39-C4FD6E608A1C%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=WORK._TEMP out=Work.preProcessedData;
	by Month;
run;

proc arima data=Work.preProcessedData plots=none out=work.ARMAX210_AllX;
	identify var=_y_fit(1) crosscorr=(Mean_Air_Temp(1) Min_Air_Temp(1) 
		Max_Air_Temp(1) Mean_Precipitation(1) );;
	estimate p=(1 2) input=(Mean_Air_Temp Min_Air_Temp Max_Air_Temp 
		Mean_Precipitation) method=ML;
	forecast lead=12 back=0 alpha=0.05 id=Month interval=month nooutall;
	run;

quit;

proc delete data=Work.preProcessedData;
run;