/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '10/9/23, 12:31 PM' 
 * Generated by 'chand' 
 * Generated on server 'CHANDU.HSD1.CT.COMCAST.NET' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:60167/main?locale=en_US&zone=GMT-04%253A00&sutoken=%257B0147E48F-0D68-4711-B331-A13FFBE6F2C3%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.COFFEEMG out=Work.preProcessedData;
	by Month;
run;

proc arima data=Work.preProcessedData plots
    (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecastonly));
	identify var=Mean_Price(1) crosscorr=(Max_Air_Temp(1) );
	estimate p=(1) input=(Max_Air_Temp) method=ML;
	forecast lead=12 back=12 alpha=0.05 id=Month interval=month;
	outlier;
	run;
quit;

/* Unit root test analysis */
proc arima data=Work.preProcessedData plots=none;
	ods select StationarityTests;
	identify var=Mean_Price(1) stationarity=(adf=2);
	run;
quit;

proc delete data=Work.preProcessedData;
run;